### Employees

# Alle Mitarbeiter abrufen
GET http://localhost:8080/api/employees

### Neuen Mitarbeiter erstellen
POST http://localhost:8080/api/employees
Content-Type: application/json

{
    "first_name": "Max",
    "last_name": "Mustermann",
    "email": "max@example.com",
    "password": "secret123",
    "department_id": 1
}

### Einzelnen Mitarbeiter abrufen
GET http://localhost:8080/api/employees/1

### Mitarbeiter aktualisieren
PUT http://localhost:8080/api/employees/1
Content-Type: application/json

{
    "first_name": "Maximilian",
    "last_name": "Mustermann",
    "email": "maximilian@example.com",
    "password": "newpassword123",
    "department_id": 1
}

### Mitarbeiter löschen
DELETE http://localhost:8080/api/employees/1
