### ShiftBlocks

# Alle Schichtblöcke abrufen
GET http://localhost:8080/api/shiftblocks

### Neuen Schichtblock erstellen
POST http://localhost:8080/api/shiftblocks
Content-Type: application/json

{
    "name": "Woche 1",
    "start_date": "2024-01-22T00:00:00Z",
    "employee_id": 1,
    "description": "Erste Januarwoche",
    "monday": {
        "shift_type_id": 1
    },
    "tuesday": {
        "shift_type_id": 2
    },
    "wednesday": {
        "shift_type_id": 1
    },
    "thursday": {
        "shift_type_id": 2
    },
    "friday": {
        "shift_type_id": 1
    },
    "saturday": {
        "shift_type_id": 3
    },
    "sunday": {
        "shift_type_id": 3
    }
}

### Einzelnen Schichtblock abrufen
GET http://localhost:8080/api/shiftblocks/1

### Schichtblock aktualisieren
PUT http://localhost:8080/api/shiftblocks/1
Content-Type: application/json

{
    "name": "Woche 1 Update",
    "start_date": "2024-01-22T00:00:00Z",
    "employee_id": 1,
    "description": "Erste Januarwoche aktualisiert",
    "monday": {
        "shift_type_id": 2
    },
    "tuesday": {
        "shift_type_id": 1
    },
    "wednesday": {
        "shift_type_id": 2
    },
    "thursday": {
        "shift_type_id": 1
    },
    "friday": {
        "shift_type_id": 2
    },
    "saturday": {
        "shift_type_id": 3
    },
    "sunday": {
        "shift_type_id": 3
    }
}

### Schichtblock löschen
DELETE http://localhost:8080/api/shiftblocks/1